### ISSUE TITLE
退格键问题

### ISSUE THREAD

**Issue by kongxy-n** [z0gSh1u/expshell#1]
运行您的shell后，退格键会直接被读取为^?，不会生效。并且退出shell后，也这样。
重新打开终端才会恢复正常。
是因为getline的问题嘛？

**Comment by z0gSh1u** [comment]
由于某些 SSH 工具发送 Backspace 的方式与操作系统上不同，退格会被显示为 ^H，需要换用 Ctrl+Backspace 才能正确退格。因此，使用了这一行代码来修复这个问题：

https://github.com/z0gSh1u/expshell/blob/f3e65fa0fe8749dab7d826c05cf41165dff68701/ExpShell.cpp#L436

但这带来另一个问题：SSH 的退格问题被修复了，操作系统上直接进行退格却会出现错误。

感谢你的反馈！删除该行代码即可解决问题。最新的 commit 已经注释了该行代码。
